# Auto-generated by the cold-frame Release workflow (packaging/homebrew/bump-tap.sh) — do not edit.
# Installs the self-contained binary (CLI + MCP in one file; no Python, offline). macOS = Apple
# Silicon only (Intel is out of scope). `brew install coldzero94/coldframe/cold-frame`.
class ColdFrame < Formula
  desc "Local-first ownable memory layer for LLM agents (one offline SQLite file)"
  homepage "https://github.com/coldzero94/cold-frame"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/coldzero94/cold-frame/releases/download/v0.1.0/cold-frame-macos-arm64"
      sha256 "744901491f18dd1c2f712510214d8cc93472ea6aedbfaeebe285cd6f62fd8bdd"
    end
  end
  on_linux do
    url "https://github.com/coldzero94/cold-frame/releases/download/v0.1.0/cold-frame-linux-x86_64"
    sha256 "1b4e61b23c5795214f96552a905f13875c9285e624e82f1f2bbfaf53b43bd1ea"
  end

  def install
    bin.install Dir["cold-frame-*"].first => "cold-frame"
    chmod 0755, bin/"cold-frame"
  end

  test do
    assert_match version, shell_output("#{bin}/cold-frame --version")
  end

  def caveats
    <<~EOS
      Turn on AUTOMATIC memory in Claude Code (recall every session, capture as you work):
        cold-frame hook install
        claude mcp add cold-frame -- cold-frame mcp

      Your memory lives in ~/.cold-frame/memory.db — one file, yours, offline. Browse it:
        cold-frame ui
    EOS
  end
end
