# Auto-generated by the cold-frame Release workflow (packaging/homebrew/bump-tap.sh) — do not edit.
# Installs the self-contained binary (CLI + MCP in one file; no Python, offline). macOS = Apple
# Silicon only (Intel is out of scope). `brew install coldzero94/coldframe/cold-frame`.
class ColdFrame < Formula
  desc "Local-first ownable memory layer for LLM agents (one offline SQLite file)"
  homepage "https://github.com/coldzero94/cold-frame"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/coldzero94/cold-frame/releases/download/v0.1.1/cold-frame-macos-arm64"
      sha256 "828beabd845af5eab46621c4f36c6eedc9f7a00e5688d45c7669aa4ded2bad03"
    end
  end
  on_linux do
    url "https://github.com/coldzero94/cold-frame/releases/download/v0.1.1/cold-frame-linux-x86_64"
    sha256 "4fa219140a653e50f6ce3278c122345961874f2ef894e6d9cdcdefb780195525"
  end

  def install
    bin.install Dir["cold-frame-*"].first => "cold-frame"
    chmod 0755, bin/"cold-frame"
  end

  test do
    assert_match "0.1.1", shell_output("#{bin}/cold-frame --version")
  end

  def caveats
    <<~EOS
      Turn on AUTOMATIC memory in Claude Code (recall every session, capture as you work):
        cold-frame hook install
        claude mcp add cold-frame -- cold-frame mcp

      Your memory lives in ~/.cold-frame/memory.db — one file, yours, offline. Browse it:
        cold-frame ui
    EOS
  end
end
